### ISSUE TITLE
npm: command not found

### ISSUE THREAD

**Issue by zhouxuan009** [zhouxuan009/CS179J-Team07#21]
jetbot@jetbot:~/CS179J-Team07/src/slam/openvslam/viewer$ npm install
-bash: npm: command not found

**Comment by ctsan005** [comment]
npm is not installed by default, so you need to install it yourself in nano.

Here is a command to install the npm and node for nano, change the version number will install a different version of npm and node. I tested with version 12 and it worked on my side, other version I have no knowledge on.

command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

**Comment by zhouxuan009** [comment]
After I run the command you mentioned, it gave the message

```
...
...
Hit:15 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease      
Hit:16 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Get:20 https://deb.nodesource.com/node_12.x bionic/main arm64 Packages [767 B]
Fetched 5,351 B in 4s (1,274 B/s)                            
Reading package lists... Done

## Run `sudo apt-get install -y nodejs` to install Node.js 12.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

```

Did you meet this before ?

**Comment by ctsan005** [comment]
That I don't think I see that on my side. Maybe follow the instruction and install the extra package. Not sure do I have those functions before I install the npm and node.
