### ISSUE TITLE
Could someone pushed the test for reinforcement learning environment code  ?

### ISSUE THREAD

**Issue by zhouxuan009** [zhouxuan009/CS179J-Team07#3]
Could someone pushed the test for reinforcement learning environment code  ?
commit 6f6319292ac67d03a1303f8dba954b9ab8fff85c

**Comment by eunc** [comment]
It's in my branch, this line from the stable_baselines.env_checker module tests it
`check_env(env, warn=True)`

**Comment by eunc** [comment]
Added code for further testing under that line in robot_env.py
