### ISSUE TITLE
Bugs when installing stable-baselines on the jetbot

### ISSUE THREAD

**Issue by zhouxuan009** [zhouxuan009/CS179J-Team07#4]
```
jetbot@jetbot:~$ pip3 install opencv-python
Collecting opencv-python
  Could not find a version that satisfies the requirement opencv-python (from versions: )
No matching distribution found for opencv-python

```
Actually it's because that the gym has the required prerequisite opencv-python
actually we have opencv installed before on our bot

There is some issues under gym which may provide some possible solutions
https://github.com/openai/gym/issues/1762

**Comment by zhouxuan009** [comment]
the architecture of the bot is aarch64, seems that pip provided specific package opencv-python-aarch64. The nomal opencv-python does not work

**Comment by zhouxuan009** [comment]
If I use 
```
pip3 install gym==0.15.3 --no-dependencies
```
gym will be installed, but when I want to import gym, it says that it needs numpy dependency
It's wired because I can run numpy in jupyter notebook
When I use python in the terminal, i cannot even import numpy

I think that's because the jupyter notebook is not using the default python3 as the kernel. Instead, the jupyter notebook has its own kernel.

So what should I do is to find the jupyter notebook python kernel, and then modify it

https://jupyter-client.readthedocs.io/en/stable/kernels.html

**Comment by zhouxuan009** [comment]
Find that instructions like 'pip install' can also be run in the jupyter notebook blocks. Keep trying !

**Comment by zhouxuan009** [comment]
The problem may lies in the installation of scipy
I need to find the proper python version the jupyter notebook is using
go into /usr/bin, we can see many python executable files
I run the python3.6 and it can import packages like numpy and torch
it's the python we are using

Then I need to configure the pip for this python
go into /usr/local/bin and we can find some txt files pip*
I create a new pip3.6 file
```
#!/usr/bin/python3.6
  
# -*- coding: utf-8 -*-
import re
import sys

from pip._internal.cli.main import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main()
```

then I pip list

**Comment by zhouxuan009** [comment]
anything of python3.6 in under /home/jetbot/.local/lib/python3.6/site-packages

**Comment by zhouxuan009** [comment]
https://stackoverflow.com/questions/33848709/cant-install-scipy-freezes-on-running-setup-py-install-for-scipy

installing scipy is very slow, taking up to one hour ...
just wait with patience

**Comment by zhouxuan009** [comment]
sudo -H python3.6 -m pip install scipy --force
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/04/ab/e2eb3e3f90b9363040a3d885ccc5c79fe20c5b8a3caa8fe3bf47ff653260/scipy-1.4.1.tar.gz (24.6MB)
    100% |████████████████████████████████| 24.6MB 13kB/s 
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... \

|
|
-

done
  Stored in directory: /root/.cache/pip/wheels/2a/b3/e6/29f19bec941bf1c135fcf94df893b45cc30a7f58a57714e503
Successfully built scipy
Installing collected packages: scipy

Successfully installed scipy-1.4.1

it takes an hour :)

**Comment by zhouxuan009** [comment]
```
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()
```

```
---------------------------------------------------------------------------
NoSuchDisplayException                    Traceback (most recent call last)
<ipython-input-1-ae18def96b83> in <module>
      3 env.reset()
      4 for _ in range(1000):
----> 5     env.render()
      6     env.step(env.action_space.sample()) # take a random action
      7 env.close()
/usr/local/lib/python3.6/dist-packages/gym/core.py in render(self, mode, **kwargs)
    231 
    232     def render(self, mode='human', **kwargs):
--> 233         return self.env.render(mode, **kwargs)
    234 
    235     def close(self):
/usr/local/lib/python3.6/dist-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
    172 
    173         if self.viewer is None:
--> 174             from gym.envs.classic_control import rendering
    175             self.viewer = rendering.Viewer(screen_width, screen_height)
    176             l, r, t, b = -cartwidth / 2, cartwidth / 2, cartheight / 2, -cartheight / 2
/usr/local/lib/python3.6/dist-packages/gym/envs/classic_control/rendering.py in <module>
     23 
     24 try:
---> 25     from pyglet.gl import *
     26 except ImportError as e:
     27     raise ImportError('''
~/.local/lib/python3.6/site-packages/pyglet/gl/__init__.py in <module>
    237     # trickery is for circular import
    238     _pyglet.gl = _sys.modules[__name__]
--> 239     import pyglet.window
~/.local/lib/python3.6/site-packages/pyglet/window/__init__.py in <module>
   1894 if not _is_pyglet_docgen:
   1895     pyglet.window = sys.modules[__name__]
-> 1896     gl._create_shadow_window()
   1897 
~/.local/lib/python3.6/site-packages/pyglet/gl/__init__.py in _create_shadow_window()
    206 
    207     from pyglet.window import Window
--> 208     _shadow_window = Window(width=1, height=1, visible=False)
    209     _shadow_window.switch_to()
    210 
~/.local/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py in __init__(self, *args, **kwargs)
    164                     self._event_handlers[message] = func
    165 
--> 166         super(XlibWindow, self).__init__(*args, **kwargs)
    167 
    168         global _can_detect_autorepeat
~/.local/lib/python3.6/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    499 
    500         if not display:
--> 501             display = get_platform().get_default_display()
    502 
    503         if not screen:
~/.local/lib/python3.6/site-packages/pyglet/window/__init__.py in get_default_display(self)
   1843         :rtype: `Display`
   1844         """
-> 1845         return pyglet.canvas.get_display()
   1846 
   1847 if _is_pyglet_docgen:
~/.local/lib/python3.6/site-packages/pyglet/canvas/__init__.py in get_display()
     80 
     81     # Otherwise, create a new display and return it.
---> 82     return Display()
     83 
     84 if _is_pyglet_docgen:
~/.local/lib/python3.6/site-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
     84         self._display = xlib.XOpenDisplay(name)
     85         if not self._display:
---> 86             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
     87 
     88         screen_count = xlib.XScreenCount(self._display)
NoSuchDisplayException: Cannot connect to "None"
```

**Comment by eunc** [comment]
for stable-baselines
build opencv from source
install scipy
install stable-baselines --no-dependencies
install cloudpickle
install pandas
install pyglet
