### ISSUE TITLE
Question about calibration.py of coodinate system

### ISSUE THREAD

**Issue by zhouxuan009** [zhouxuan009/CS179J-Team07#5]
After reviewing this code, i have some questions about the code
Is the function 'calibration_straight' used to get the conversion relationship of robot unit and meters?
Is the funcion 'calibration_spin' used to get the time of each spin ?

**Comment by ctsan005** [comment]
The function of calibration_straight is to capture the true speed of the car. So using the result can allow you to convert the robot unit to the SI unit. But that depends on what unit the user put in the input. It does not have to be meter.

For calibration_spin, you are correct. The user will call the function and enter how many times they want the car to spin and press enter when the car reaches that amount of spin to stop it. It will return the time to perform 1 spin. So, the more the car spins during calibration, the more exact the spinning time will be.

**Comment by zhouxuan009** [comment]
Got it , thx !
