### ISSUE TITLE
Problem about the infomation update of the spinning robot in coordinate system

### ISSUE THREAD

**Issue by zhouxuan009** [zhouxuan009/CS179J-Team07#6]
In the file coordinate_planning1.py

```
            if(prob_left > 0.5):    #thinking to use machine learning model to determine do the car need to turn left
                while(prob_left > 0.5):
                    spin_left()
                    #prob_left = #need update
                    sleep(0.1)
                    curr_angle = check_angle(curr_angle - (spin_time/0.1) * 360)  #make sure the angle is between -180 to 180 degree
                
                straight()
                sleep(0.5)
                update_info_straight(curr_x, curr_y,curr_angle,0.5)
```

When the car spins, only the curr_angle is updated
However, should the curr_x and curr_y also be updated ?

**Comment by ctsan005** [comment]
My idea is spin only change the angle without moving the x and y coordinate while turn will move the angle as well the x and y coordinate. 
There will be a lot of math behind turning, so the current version only use spin to perform changing in angle then move forward with it.

**Comment by zhouxuan009** [comment]
Thank u for your answer. This issue can be considered as an enhancement in the future. We can keep this issue
