### ISSUE TITLE
What's spin time ? Do we need to consider the distance of moving forward when the car spins?

### ISSUE THREAD

**Issue by zhouxuan009** [zhouxuan009/CS179J-Team07#8]
Is the spin time the time during which the car takes a turn ?
What's more, according to the physical caculation, when the speed of the left motor and right motor differs, the car just turn around at the same place. So I think the distance of moving forward when the car spins can be ignored

**Comment by ctsan005** [comment]
Instead of taking a turn, it just spin from the current location without changing the x or y coordinate. But the general idea is correct, spin time is how long the car will need to spin one cycle

**Comment by zhouxuan009** [comment]
I have tested. The value is about 3.1

**Comment by ctsan005** [comment]
Got it, but is this the time it takes for using the robot.left(0.5) speed?

**Comment by zhouxuan009** [comment]
yes
